### ISSUE TITLE
errors compiling dstats with dmd 2.059 beta

### ISSUE THREAD

**Issue by jordisayol** [dsimcha/dstats#1]
sort.d(947): Error: template dstats.sort.prepareForSorting matches more than one template declaration, sort.d(165):prepareForSorting(alias comp,T) if (!isFloatingPoint!(ElementType!(T)) || !isSimpleComparison!(comp)) and sort.d(186):prepareForSorting(alias comp,F) if (is(F == double[]) || is(F == float[]) && isSimpleComparison!(comp))

sort.d(354): Error: template instance dstats.sort.insertionSort!(absGreater,double[],double[][],ulong[],double[]) error instantiating

regress.d(1138):        instantiated from here: qsort!(absGreater,double[],double[][],ulong[],double[])

sort.d(360): Error: template dstats.sort.prepareForSorting matches more than one template declaration, sort.d(165):prepareForSorting(alias comp,T) if (!isFloatingPoint!(ElementType!(T)) || !isSimpleComparison!(comp)) and sort.d(186):prepareForSorting(alias comp,F) if (is(F == double[]) || is(F == float[]) && isSimpleComparison!(comp))

regress.d(1138): Error: template instance dstats.sort.qsort!(absGreater,double[],double[][],ulong[],double[]) error instantiating

**Comment by dsimcha** [comment]
Thanks for the report.  I have a fix on my hard drive but am waiting for some other regressions to get fixed so I can test and commit all the 2.059-related fixes to Github.

**Comment by jordisayol** [comment]
the dmd 2.059 is released. Can you upload all fixes please? If possible, make it compilable with scid.

**Comment by dsimcha** [comment]
I'm still working on them.  I'll upload them as soon as they're ready.  The
latest release completely changed how circular dependencies are handled,
leading to some complicated workarounds that I'm not finished implementing.
On Apr 13, 2012 6:30 PM, "jordisayol" <
reply@reply.github.com>
wrote:

**Comment by jordisayol** [comment]
Last commit allow to properly compile dstats, if not depends on scid library.

Get these errors If compiled with -version=scid flag:

```
$ dmd -O -inline -release -lib -oflibdstats.a -version=scid *.d
base.d(1496): Error: module matvec is in file 'scid/matvec.d' which cannot be read
base.d(1496): Error: module exception is in file 'scid/exception.d' which cannot be read
alloc.d(1682): Error: module regionallocator is in file 'scid/internal/regionallocator.d' which cannot be read
```

"scid/matvec.d", "scid/exception.d" and "scid/internal/regionallocator.d" modules do not exist on scid Github.

Also, when trying to compile with unittext, get this error:

```
$ rdmd -inline -release -unittest *.d
dstats/alloc.d(2876): Error: constructor core.thread.Thread.this called with argument types:
    ((void function()))
matches both:
    core.thread.Thread.this(void function() fn, ulong sz = cast(ulong)0)
and:
    core.thread.Thread.this(void delegate() dg, ulong sz = cast(ulong)0)
kolmDist is scheduled for deprecation.  Please use kolmogorovDistrib instead.
```

**Comment by dsimcha** [comment]
I fixed the issue with dstats.alloc when compiling w/o -version=scid.  The other issue is almost surely caused by your import paths for SciD not being set up right.  You may need to pass a -I switch to DMD.

**Comment by jordisayol** [comment]
I've properly passed -I switch to dmd.

The problem is that none of the following modules exist in the scid project, but alloc.d and base.d try to import them:

```
scid/internal/regionallocator.d
scid/matvec.d
scid/exception.d
```

Are we talking about the same scid project?
https://github.com/kyllingstad/scid
